"""Exact linear-algebra helpers for the TN-path novelty audit.

The full non-reduction arguments live in ``docs/TN_NOVELTY_AUDIT.md``.
This module exposes the integer matrices used in the Majorana part of that
argument so the finite-dimensional algebra remains regression tested.
"""

from __future__ import annotations

import numpy as np


_LOCAL_J = np.asarray([[0, 1], [-1, 0]], dtype=int)
_LOCAL_X = np.asarray([[0, 1], [1, 0]], dtype=int)
_LOCAL_Z = np.asarray([[1, 0], [0, -1]], dtype=int)


def diagonal_majorana_generators(sites: int) -> tuple[np.ndarray, ...]:
    """Return the real parts of ``M(E_i)/i`` in site-major ordering.

    For a real diagonal number-conserving generator
    ``D = diag(d_1, ..., d_n)``, its Majorana coefficient matrix is

    ``M(D) = i * direct_sum_i(d_i * J)``,

    up to the irrelevant scalar ``trace(D)/2``.  Here ``J`` is the real
    ``2 x 2`` skew matrix returned in each occupied block.
    """

    if sites < 1:
        raise ValueError("sites must be positive")

    dimension = 2 * sites
    generators: list[np.ndarray] = []
    for site in range(sites):
        matrix = np.zeros((dimension, dimension), dtype=int)
        start = 2 * site
        matrix[start : start + 2, start : start + 2] = _LOCAL_J
        generators.append(matrix)
    return tuple(generators)


def common_anticommutant_basis(sites: int) -> tuple[np.ndarray, ...]:
    """Return an integer basis for matrices anticommuting with every site block.

    The common anticommutant is block diagonal.  On each site its block is
    ``a Z + b X``; hence its complex dimension is exactly ``2 * sites``.
    """

    if sites < 1:
        raise ValueError("sites must be positive")

    dimension = 2 * sites
    basis: list[np.ndarray] = []
    for site in range(sites):
        start = 2 * site
        for local in (_LOCAL_Z, _LOCAL_X):
            matrix = np.zeros((dimension, dimension), dtype=int)
            matrix[start : start + 2, start : start + 2] = local
            basis.append(matrix)
    return tuple(basis)


def anticommutant_constraint_matrix(sites: int) -> np.ndarray:
    """Build the exact integer linear system for ``K L_i + L_i K = 0``.

    Unknown entries of ``K`` are flattened in row-major order.  The returned
    matrix may contain redundant rows; its nullspace is the common
    anticommutant generated by :func:`common_anticommutant_basis`.
    """

    generators = diagonal_majorana_generators(sites)
    dimension = 2 * sites
    variable_count = dimension * dimension
    rows: list[np.ndarray] = []

    for generator in generators:
        for row in range(dimension):
            for column in range(dimension):
                equation = np.zeros(variable_count, dtype=int)
                for inner in range(dimension):
                    equation[row * dimension + inner] += generator[inner, column]
                    equation[inner * dimension + column] += generator[row, inner]
                rows.append(equation)
    return np.asarray(rows, dtype=int)
